# Generated by Django 4.2.11 on 2025-03-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_task_tasker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasker',
        ),
        migrations.AddField(
            model_name='task',
            name='taskers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistapp.taskers'),
        ),
    ]
