# Generated by Django 4.2.11 on 2025-03-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0004_remove_task_tasker_task_taskers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolistapp.taskers'),
        ),
    ]
